MCU = STM32F072 
BOOTLOADER = stm32-dfu
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
LTO_ENABLE = yes
CIE1931_CURVE = no
WS2812_DRIVER = pwm
VIA_ENABLE = yes

